---

- name: "dir to download aws-discovery-agent.tar.gz"
  file:
    path: "{{ app_disco_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: no

- name: "fetch AWS Cloudwatch agent archive if not already installed"
  get_url:
    url: "{{ app_disco_src_url }}"
    dest: "{{ app_disco_zip }}"
    mode: 550

- name: "Unzip app_disco agent archive"
  unarchive:
    dest: "{{ app_disco_dir }}"
    remote_src: yes
    src: "{{ app_disco_zip }}"

- name: "Install app_disco agent from archive"
  command: bash install -r us-west-2 -k "{{ app_disco_key_key }}" -s "{{ app_disco_key_secret }}" -p true -c true -b true
  args:
    chdir: "{{ app_disco_dir }}"
